name: cr_mentions
description: A great package for mentioning people in texts in different ways

version: 0.0.1+1
homepage: https://github.com/Cleveroad/cr_mentions

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  dartx: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: